### ISSUE TITLE
Add support for windows

### ISSUE THREAD

**Issue by Brools** [janjongboom/mbed-simulator#13]
Excellent work! I very much enjoyed the online simulator.
I tried to install locally on windows 10, but it fails in libmbed.js when trying to spawn emcc process.
emcc is in my path and emcc calls works from cmd line. It gives a NOENT error.
When changing the line to
`let cmd = spawn('emcc.bat', args);`
It finds the emcc.bat, but now complains on the long input (args is very long).
This comes down to windows limits. I found the following [emcc.bat command line too long](https://github.com/kripken/emscripten/issues/4438)
I dont have much experience with nodejs, but it is possible to stream the args to the process through stdin?
I guess that also depends on emcc.

**Comment by janjongboom** [comment]
@Brools thanks for the report; will see what I can do.

**Comment by janjongboom** [comment]
Fixed in e5ff2b6  and released under v1.4.0 in npm!
