### ISSUE TITLE
Runtime failures, appear to be peripheral related

### ISSUE THREAD

**Issue by woobagooba** [janjongboom/mbed-simulator#34]
All the demos appear to compile correctly.  

Some are failing at run-time notably Temperature / Humidy and LoRaWAN.  Others are failing as well.

Here is the Temp /Hum web console ...

![sht31](https://user-images.githubusercontent.com/3648022/56966431-19ad5100-6b2d-11e9-80af-d6f1164164e3.JPG)

And LoRaWAN ... 

![LoraWAN](https://user-images.githubusercontent.com/3648022/56966442-1f0a9b80-6b2d-11e9-9b38-bb0199461057.JPG)

**Comment by janjongboom** [comment]
Fixed in https://github.com/janjongboom/mbed-simulator/pull/35 thanks for reporting. Didn't properly run the regression tests as this was not deployed on production, but have now.
