### ISSUE TITLE
Mbed Simulator giving windows error 87 Parameter is incorrect

### ISSUE THREAD

**Issue by Selenatabbara** [janjongboom/mbed-simulator#41]
Hello, 
I went through the steps provided in the README.md file to install Emscripten and install mbed-simulator through git using:
```
$ git clone https://github.com/janjongboom/mbed-simulator.git
$ cd mbed-simulator
$ npm install
$ npm install . -g
```
I have tried to build the blinky example using: 
`$ node cli.js -i demos\blinky -o out --launch 
`
But I have this error
![image](https://user-images.githubusercontent.com/30468952/62288375-27d47b80-b454-11e9-8498-a5b927325281.png)

I am using : 
![image](https://user-images.githubusercontent.com/30468952/62288682-d5e02580-b454-11e9-80a7-aa7aa8db452a.png)

**Comment by janjongboom** [comment]
Hi @Selenatabbara, this is due to path length limits on Windows. Move the mbed-simulator folder to a folder that's shorter (e.g. `C:\mbed-simulator`). I'll add a note in the README.
