### ISSUE TITLE
potentiometer real time

### ISSUE THREAD

**Issue by cabelotaina** [janjongboom/mbed-simulator#46]
I'm using this simulator to do some study for my master.

And I'm trying to do three potentiometers change the color of the ST7789H2, its nice and works very well. The problem is the potentiometer only changes the color when I release the slider. Why it happens? This is normal or have some connection with the fact the simulator isn’t real time? If I'm using a real toolkit with real stuff this happens in same way? Sorry if this is not the correct place to do this questions...

Here is my code: https://simulator.mbed.com/#user_1592168676516

And this is the app:

![image](https://user-images.githubusercontent.com/1827173/84604046-8f8c8d00-ae93-11ea-9c05-4bf402a3e34a.png)

Thx in advance

**Comment by janjongboom** [comment]
@cabelotaina That's the way the slider element works currently, only updates the value after you release it. https://github.com/armmbed/mbed-simulator might be able to help you further, as that's where development is done now.
